# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ include "embedding-usvc.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  lookupPolicy:
    local: true
